version: '3.8'

services:
  amaster:
    build:
      context: https://github.com/Tikomatura/AMaster.git
      dockerfile: Dockerfile
    image: tikomatura/amaster:latest
    container_name: amaster
    restart: unless-stopped
    user: "999:993"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_OWNER_ID=${DISCORD_OWNER_ID}
      - MUSIC_DIR=/music
    volumes:
      - /srv/docker/music:/music
    working_dir: /app
