version: '3.8'

services:
  amaster:
    build:
      context: https://github.com/Tikomatura/AMaster.git
      dockerfile: Dockerfile
    image: tikomatura/amaster:latest
    container_name: amaster
    restart: unless-stopped
    user: "999:993"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_OWNER_ID=${DISCORD_OWNER_ID}
      - MUSIC_DIR=/music
      - YTDL_COOKIES_PATH=/app/.yt_cookies.txt
    volumes:
      - /srv/docker/navidrome/music:/music
      - ./.yt_cookies.txt:/app/.yt_cookies.txt:ro
    working_dir: /app
